import './globals.css'
import 'remixicon/fonts/remixicon.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/partials/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-5xl mx-auto py-16">
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
